name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run:
          npm install

      - name: Build site
        run: |
          npm run build

      - name: Prepare publish directory and rewrite _next to next
        run: |
          rm -rf public
          mkdir public
          cp -r out/* public/
          # Move _next to next
          if [ -d public/_next ]; then mv public/_next public/next; fi
          # Rewrite all references to /_next/ as /next/ in all HTML, JS, and CSS files
          find public -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) -exec sed -i 's|/_next/|/next/|g' {} +
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: jadams.pw
          enable_jekyll: true